-- ==========================================
-- V1__criar_tabelas.sql
-- Oracle
-- ==========================================

-- TABELA PAUTA
CREATE TABLE PAUTA (
                       ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       TITULO        VARCHAR2(255) NOT NULL,
                       DESCRICAO     VARCHAR2(1000) NOT NULL,
                       CRIADA_EM     TIMESTAMP DEFAULT FROM_TZ(CAST(CURRENT_TIMESTAMP AS TIMESTAMP), 'America/Sao_Paulo') NOT NULL
);

-- TABELA SESSAO_VOTACAO
CREATE TABLE SESSAO_VOTACAO (
                                ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                PAUTA_ID      NUMBER NOT NULL,
                                ABERTA_EM     TIMESTAMP NOT NULL,
                                FECHA_EM      TIMESTAMP NOT NULL,
                                STATUS        VARCHAR2(20) NOT NULL,

                                CONSTRAINT FK_SESSAO_PAUTA
                                    FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID)
);

-- TABELA VOTO
CREATE TABLE VOTO (
                      ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      PAUTA_ID      NUMBER NOT NULL,
                      CPF           VARCHAR2(11) NOT NULL,
                      VOTO          VARCHAR2(3) NOT NULL,
                      VOTADO_EM     TIMESTAMP DEFAULT FROM_TZ(CAST(CURRENT_TIMESTAMP AS TIMESTAMP), 'America/Sao_Paulo') NOT NULL,

                      CONSTRAINT FK_VOTO_PAUTA
                          FOREIGN KEY (PAUTA_ID) REFERENCES PAUTA(ID),

                      CONSTRAINT UK_VOTO_PAUTA_CPF
                          UNIQUE (PAUTA_ID, CPF),

                      CONSTRAINT CK_VOTO_VALOR
                          CHECK (VOTO IN ('SIM', 'NAO'))
);

-- INDEXES (performance)
CREATE INDEX IDX_VOTO_PAUTA ON VOTO (PAUTA_ID);
CREATE INDEX IDX_VOTO_CPF ON VOTO (CPF);
